jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

spring:

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/finance_tracker_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin_password}
    driver-class-name: org.postgresql.Driver



#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG